import 'phrase.dart';
import 'scenario.dart';

/// Curated bilingual phrases grouped by scenario. One tap shows the opposite
/// language instantly without waiting for the model.
const kPhrasebook = <Phrase>[
  Phrase(
    id: 'gen_hello',
    scenario: Scenario.general,
    en: 'Hello.',
    tr: 'Merhaba.',
  ),
  Phrase(
    id: 'gen_thanks',
    scenario: Scenario.general,
    en: 'Thank you.',
    tr: 'Tesekkur ederim.',
  ),
  Phrase(id: 'gen_yes', scenario: Scenario.general, en: 'Yes.', tr: 'Evet.'),
  Phrase(id: 'gen_no', scenario: Scenario.general, en: 'No.', tr: 'Hayir.'),
  Phrase(
    id: 'gen_help',
    scenario: Scenario.general,
    en: 'Can you help me?',
    tr: 'Bana yardim edebilir misiniz?',
  ),
  Phrase(
    id: 'gen_repeat',
    scenario: Scenario.general,
    en: 'Could you repeat that, please?',
    tr: 'Lutfen tekrar eder misiniz?',
  ),
  Phrase(
    id: 'gen_slow',
    scenario: Scenario.general,
    en: 'Please speak more slowly.',
    tr: 'Lutfen daha yavas konusun.',
  ),
  Phrase(
    id: 'gen_understand',
    scenario: Scenario.general,
    en: 'I do not understand.',
    tr: 'Anlamiyorum.',
  ),
  Phrase(
    id: 'airport_gate',
    scenario: Scenario.airport,
    en: 'Where is my gate?',
    tr: 'Kapim nerede?',
  ),
  Phrase(
    id: 'airport_boarding',
    scenario: Scenario.airport,
    en: 'Has boarding started?',
    tr: 'Ucus icin binis basladi mi?',
  ),
  Phrase(
    id: 'airport_delay',
    scenario: Scenario.airport,
    en: 'Is my flight delayed?',
    tr: 'Ucusum gecikti mi?',
  ),
  Phrase(
    id: 'airport_baggage',
    scenario: Scenario.airport,
    en: 'Where is baggage claim?',
    tr: 'Bagaj teslim yeri nerede?',
  ),
  Phrase(
    id: 'airport_checkin',
    scenario: Scenario.airport,
    en: 'Where can I check in?',
    tr: 'Nerede check-in yapabilirim?',
  ),
  Phrase(
    id: 'airport_security',
    scenario: Scenario.airport,
    en: 'Where is the security checkpoint?',
    tr: 'Guvenlik kontrol noktasi nerede?',
  ),
  Phrase(
    id: 'airport_seat',
    scenario: Scenario.airport,
    en: 'Can I change my seat?',
    tr: 'Koltugumu degistirebilir miyim?',
  ),
  Phrase(
    id: 'airport_connection',
    scenario: Scenario.airport,
    en: 'I have a connecting flight.',
    tr: 'Aktarmali ucusum var.',
  ),
  Phrase(
    id: 'hotel_reservation',
    scenario: Scenario.hotel,
    en: 'I have a reservation.',
    tr: 'Rezervasyonum var.',
  ),
  Phrase(
    id: 'hotel_checkin',
    scenario: Scenario.hotel,
    en: 'Can I check in now?',
    tr: 'Simdi giris yapabilir miyim?',
  ),
  Phrase(
    id: 'hotel_checkout',
    scenario: Scenario.hotel,
    en: 'What time is checkout?',
    tr: 'Cikis saati kacta?',
  ),
  Phrase(
    id: 'hotel_key',
    scenario: Scenario.hotel,
    en: 'My room key does not work.',
    tr: 'Oda anahtarim calismiyor.',
  ),
  Phrase(
    id: 'hotel_wifi',
    scenario: Scenario.hotel,
    en: 'What is the Wi-Fi password?',
    tr: 'Wi-Fi sifresi nedir?',
  ),
  Phrase(
    id: 'hotel_taxi',
    scenario: Scenario.hotel,
    en: 'Can you call a taxi?',
    tr: 'Taksi cagirabilir misiniz?',
  ),
  Phrase(
    id: 'hotel_water',
    scenario: Scenario.hotel,
    en: 'There is no hot water.',
    tr: 'Sicak su yok.',
  ),
  Phrase(
    id: 'hotel_quiet',
    scenario: Scenario.hotel,
    en: 'Can I have a quieter room?',
    tr: 'Daha sessiz bir oda alabilir miyim?',
  ),
  Phrase(
    id: 'customs_passport',
    scenario: Scenario.customs,
    en: 'Here is my passport.',
    tr: 'Pasaportum burada.',
  ),
  Phrase(
    id: 'customs_purpose',
    scenario: Scenario.customs,
    en: 'I am here for tourism.',
    tr: 'Turizm icin buradayim.',
  ),
  Phrase(
    id: 'customs_duration',
    scenario: Scenario.customs,
    en: 'I will stay for one week.',
    tr: 'Bir hafta kalacagim.',
  ),
  Phrase(
    id: 'customs_hotel',
    scenario: Scenario.customs,
    en: 'I am staying at this hotel.',
    tr: 'Bu otelde kaliyorum.',
  ),
  Phrase(
    id: 'customs_declare',
    scenario: Scenario.customs,
    en: 'I have nothing to declare.',
    tr: 'Beyan edecek bir seyim yok.',
  ),
  Phrase(
    id: 'customs_bag',
    scenario: Scenario.customs,
    en: 'This is my bag.',
    tr: 'Bu benim cantam.',
  ),
  Phrase(
    id: 'customs_ticket',
    scenario: Scenario.customs,
    en: 'Here is my return ticket.',
    tr: 'Donus biletim burada.',
  ),
  Phrase(
    id: 'customs_address',
    scenario: Scenario.customs,
    en: 'This is my address.',
    tr: 'Adresim bu.',
  ),
  Phrase(
    id: 'emergency_help',
    scenario: Scenario.emergency,
    en: 'I need help immediately.',
    tr: 'Hemen yardima ihtiyacim var.',
  ),
  Phrase(
    id: 'emergency_doctor',
    scenario: Scenario.emergency,
    en: 'I need a doctor.',
    tr: 'Doktora ihtiyacim var.',
  ),
  Phrase(
    id: 'emergency_allergy',
    scenario: Scenario.emergency,
    en: 'I have a serious allergy.',
    tr: 'Ciddi bir alerjim var.',
  ),
  Phrase(
    id: 'emergency_pain',
    scenario: Scenario.emergency,
    en: 'I have chest pain.',
    tr: 'Gogus agrim var.',
  ),
  Phrase(
    id: 'emergency_lost',
    scenario: Scenario.emergency,
    en: 'I lost my passport.',
    tr: 'Pasaportumu kaybettim.',
  ),
  Phrase(
    id: 'emergency_police',
    scenario: Scenario.emergency,
    en: 'Please call the police.',
    tr: 'Lutfen polisi arayin.',
  ),
  Phrase(
    id: 'emergency_child',
    scenario: Scenario.emergency,
    en: 'My child is missing.',
    tr: 'Cocugum kayip.',
  ),
  Phrase(
    id: 'emergency_safe',
    scenario: Scenario.emergency,
    en: 'I do not feel safe.',
    tr: 'Kendimi guvende hissetmiyorum.',
  ),
];
